# Dependabot configuration
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scale_daemon" # Location of pyproject.toml and poetry.lock
    schedule:
      interval: "daily"
    target-branch: "master"
    reviewers:
      - bcdonadio
    assignees:
      - bcdonadio
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/printer_daemon" # Location of pyproject.toml and poetry.lock
    schedule:
      interval: "daily"
    target-branch: "master"
    reviewers:
      - bcdonadio
    assignees:
      - bcdonadio
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/" # Location of your workflow files
    schedule:
      interval: "daily"
    target-branch: "master"
    reviewers:
      - bcdonadio
    assignees:
      - bcdonadio
    open-pull-requests-limit: 5 # Usually fewer actions to update
