name: Publish images

on:
  release:
    types:
      - published

jobs:
  publish_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR
    strategy:
      matrix:
        daemon:
          - name: scale-daemon
            path: ./scale_daemon
            image_name: scale-daemon
          - name: printer-daemon
            path: ./printer_daemon
            image_name: printer-daemon

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image metadata for ${{ matrix.daemon.image_name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/donadiosolutions/${{ matrix.daemon.image_name }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push ${{ matrix.daemon.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.daemon.path }}
          file: ${{ matrix.daemon.path }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
