name: Unit Test Images

permissions:
  contents: read # Workflow-level read permission for checkout

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The image tag to use for tests (e.g., ci-xxxxxxx)'
        required: true
        type: string
      platforms:
        description: 'The platforms the images were built for'
        required: true
        type: string

env:
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  unit_test_images:
    name: Run unit tests
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          - { name: "linux/amd64", runner: "ubuntu-latest" }
          - { name: "linux/arm64", runner: "ubuntu-latest-arm64" }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Load tester image from cache
        uses: docker/bake-action@v4
        with:
          files: |
            ./build.hcl
          load: true
          push: false
          set: |
            *.cache-from=type=gha
            tester.tags=tester:${{ env.IMAGE_TAG }}
            *.platform=${{ matrix.platform.name }}
          targets: tester

      - name: Run unit tests
        run: |
          docker run --rm tester:${{ env.IMAGE_TAG }}

  call_integration_test_workflow: # Renamed for clarity, this job IS the call
    name: Call Integration Test Workflow
    uses: ./.github/workflows/integration-test.yml # Reusable workflow called at job level
    needs: unit_test_images
    permissions:
      contents: read # Permissions for the token passed to the called workflow
    with:
      image_tag: ${{ inputs.image_tag }} # Use inputs from workflow_call
      platforms: ${{ inputs.platforms }} # Use inputs from workflow_call
    # secrets: inherit # If secrets need to be passed
